/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bedroom.glb 
Author: Marie (https://sketchfab.com/Polairee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bedroom-ed2bb89a47c947948ccce16f975638df
Title: bedroom
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Bedroom(props) {
  const { nodes, materials } = useGLTF('/models/bedroom.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[-0.361, 0.486, -0.092]} scale={[0.471, 0.032, 0.689]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.019']} position={[-0.361, 0.664, -0.085]} rotation={[0, 0, -Math.PI]} scale={[-0.497, 0.2, 0.728]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.022']} position={[-0.387, 0.931, -0.513]} rotation={[0.879, 0.048, 0.006]} scale={[0.196, 0.144, 0.144]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Material.016']} position={[0.143, 0.282, 0.291]} scale={[1, 0.031, 1]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['Material.012']} position={[-0.404, 1.96, -0.918]} scale={[0.064, 0.075, 0.064]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['Material.013']} position={[-0.058, 1.897, -0.735]} rotation={[1.384, 0.146, -1.481]} scale={0.005} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['Material.011']} position={[1.573, 1.184, -0.84]} rotation={[Math.PI, -1.505, Math.PI / 2]} scale={0.086} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['Material.009']} position={[-0.042, 1.828, -0.9]} rotation={[Math.PI, -1.117, Math.PI]} scale={0.086} />
      <mesh geometry={nodes.Object_46.geometry} material={materials['Material.010']} position={[-0.042, 1.828, -0.9]} rotation={[Math.PI, -1.117, Math.PI]} scale={0.086} />
      <mesh geometry={nodes.Object_141.geometry} material={materials.PaletteMaterial002} position={[-1.074, 1.301, 0.903]} rotation={[0, 0, -Math.PI / 2]} scale={[0.833, 0.694, 0.091]} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.PaletteMaterial003} position={[0.794, 1.047, -0.858]} />
      <mesh geometry={nodes.Object_172.geometry} material={materials.PaletteMaterial004} position={[1.458, 0.926, -0.141]} rotation={[-Math.PI, 0.791, -Math.PI]} scale={[0.071, 0.024, 0.091]} />
      <mesh geometry={nodes.Object_183.geometry} material={materials['Material.030']} position={[0.398, 0.847, -0.751]} scale={0.097} />
      <mesh geometry={nodes.Object_191.geometry} material={materials['Material.063']} position={[0.69, 1.843, -1.303]} scale={[0.281, 0.281, 0.077]} />
      <mesh geometry={nodes.Object_193.geometry} material={materials['Material.060']} position={[0.69, 1.843, -1.303]} scale={[0.281, 0.281, 0.077]} />
      <mesh geometry={nodes.Object_195.geometry} material={materials['Material.062']} position={[0.69, 1.843, -1.303]} scale={[0.281, 0.281, 0.077]} />
      <mesh geometry={nodes.Object_197.geometry} material={materials['Material.061']} position={[0.69, 1.843, -1.303]} scale={[0.281, 0.281, 0.077]} />
    </group>
  )
}

useGLTF.preload('/models/bedroom.glb')
